services:
  iris:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - 1972:1972
      - 52773:52773
  # python:
  #   build:
  #     context: . 
  #     dockerfile: DockerfilePython
  #   ports:
  #     - 8051:8051
  #   volumes:
  #     - ./:/app

