[project]
name = "python-fullstack"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "intersystems-irispython>=5.3.0",
    "pandas>=2.3.3",
    "sqlalchemy-iris[intersystems]>=0.16.1",
    "streamlit>=1.52.1",
]
